name: Build & Deploy

on:
    push:
        branches: [main]

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Setup Node.js
              uses: actions/setup-node@main
              with:
                  node-version: 12.x
            - name: Install Dependencies
              run: |
                  npm i -g npm
                  npm i
            - name: Build
              run: npm run build
            - name: Deploy
              run: |
                  git config --global user.name $user_name
                  git config --global user.email $user_email
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run deploy
              env:
                  user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com"
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
